figma.showUI(__html__, { width: 360, height: 480, title: 'Component Docs' });

// ─── Types ────────────────────────────────────────────────────────────────────

interface PropInfo {
  name: string;
  type: 'VARIANT' | 'BOOLEAN' | 'TEXT' | 'INSTANCE_SWAP';
  options: string[];
  defaultValue: string;
}

// ─── State (plugin-data links) ──────────────────────────────────────────────

type DocOptions = { includeProps: boolean; includeVariants: boolean; includeNotes: boolean };

const DESC_PLACEHOLDER = 'Add a description for this component…';

// Keys are private to this plugin (setPluginData, not shared).
const KEY_DOC = 'docId';       // stored on the SOURCE component/set
const KEY_SOURCE = 'sourceId'; // stored on the DOC frame
const KEY_OPTS = 'options';    // stored on the DOC frame (JSON DocOptions)
const KEY_DESC = 'description'; // stored on the DOC frame (cached text)

/** Write the bidirectional link between a source component and its doc frame. */
function linkNodes(source: BaseNode, doc: BaseNode): void {
  source.setPluginData(KEY_DOC, doc.id);
  doc.setPluginData(KEY_SOURCE, source.id);
}

/** Resolve an id to a node only if it still exists and isn't removed. */
async function resolveLiveNode(id: string): Promise<BaseNode | null> {
  if (!id) return null;
  let node: BaseNode | null = null;
  try {
    node = await figma.getNodeByIdAsync(id);
  } catch {
    return null;
  }
  if (!node) return null;
  if (node.removed) return null;
  return node;
}

/** Cache the options + description used to build a doc. */
function saveDocMeta(doc: BaseNode, opts: DocOptions, description: string): void {
  doc.setPluginData(KEY_OPTS, JSON.stringify(opts));
  doc.setPluginData(KEY_DESC, description);
}

/** Read the cached options from a doc frame, or null if absent/corrupt. */
function readDocOptions(doc: BaseNode): DocOptions | null {
  const raw = doc.getPluginData(KEY_OPTS);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as DocOptions;
  } catch {
    return null;
  }
}

function readDocSourceId(doc: BaseNode): string {
  return doc.getPluginData(KEY_SOURCE);
}

function readSourceDocId(source: BaseNode): string {
  return source.getPluginData(KEY_DOC);
}

/** True if this node was generated by us (carries a sourceId link). */
function isDocFrame(node: BaseNode): boolean {
  return node.getPluginData(KEY_SOURCE) !== '';
}

// ─── Fonts ────────────────────────────────────────────────────────────────────

async function loadFonts() {
  await Promise.all([
    figma.loadFontAsync({ family: 'Inter', style: 'Regular' }),
    figma.loadFontAsync({ family: 'Inter', style: 'Medium' }),
    figma.loadFontAsync({ family: 'Inter', style: 'Bold' }),
  ]);
}

// ─── Layout constants ─────────────────────────────────────────────────────────

const PAD_H = 24;
const MIN_CONTENT_W = 512; // col1 + col2 + col3 minimum
const COL1 = 160;
const COL2 = 100;
// COL3 = contentW - COL1 - COL2  (fills remaining space)

// ─── Width pre-calculation ────────────────────────────────────────────────────

/**
 * Measures the widest child (variant) in the component set.
 * Returns contentW = max(MIN_CONTENT_W, widest child width).
 * docW = contentW + 2 * PAD_H.
 */
function calcWidths(comp: ComponentNode | ComponentSetNode): { contentW: number; docW: number } {
  let maxW = MIN_CONTENT_W;
  if (comp.type === 'COMPONENT_SET') {
    for (const child of (comp as ComponentSetNode).children) {
      const w = (child as ComponentNode).width;
      if (w > maxW) maxW = w;
    }
  } else {
    if (comp.width > maxW) maxW = comp.width;
  }
  return { contentW: maxW, docW: maxW + PAD_H * 2 };
}

// ─── Primitives ───────────────────────────────────────────────────────────────

function rgb(hex: string): RGB {
  const n = parseInt(hex.slice(1), 16);
  return { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255 };
}

function fill(hex: string): SolidPaint {
  return { type: 'SOLID', color: rgb(hex) };
}

function frame(name: string): FrameNode {
  const f = figma.createFrame();
  f.name = name;
  f.fills = [];
  f.clipsContent = false;
  return f;
}

/**
 * Vertical stack: fixed width, hugs height.
 * Sizing modes set AFTER resize() so they win over resize()'s implicit FIXED.
 */
function vStack(f: FrameNode, w: number, gap: number, padH = 0, padV = 0) {
  f.layoutMode = 'VERTICAL';
  f.itemSpacing = gap;
  f.paddingLeft = padH;
  f.paddingRight = padH;
  f.paddingTop = padV;
  f.paddingBottom = padV;
  f.resize(w, 100);
  f.primaryAxisSizingMode = 'AUTO';   // height hugs — set after resize()
  f.counterAxisSizingMode = 'FIXED';  // width fixed — set after resize()
}

/**
 * Horizontal stack: hugs both axes.
 */
function hStack(f: FrameNode, gap: number, padH = 0, padV = 0) {
  f.layoutMode = 'HORIZONTAL';
  f.itemSpacing = gap;
  f.paddingLeft = padH;
  f.paddingRight = padH;
  f.paddingTop = padV;
  f.paddingBottom = padV;
  f.primaryAxisSizingMode = 'AUTO';
  f.counterAxisSizingMode = 'AUTO';
}

function txt(content: string, size: number, style: 'Regular' | 'Medium' | 'Bold', color = '#1A1A1A'): TextNode {
  const t = figma.createText();
  t.fontName = { family: 'Inter', style };
  t.characters = content;
  t.fontSize = size;
  t.fills = [fill(color)];
  return t;
}

function pill(label: string, bg: string, fg: string): FrameNode {
  const f = frame(`pill-${label}`);
  f.fills = [fill(bg)];
  f.cornerRadius = 4;
  hStack(f, 0, 6, 3);
  const t = figma.createText();
  t.fontName = { family: 'Inter', style: 'Medium' };
  t.characters = label;
  t.fontSize = 10;
  t.fills = [fill(fg)];
  f.appendChild(t);
  return f;
}

/** Gray badge with a ◆ icon, used for resolved instance-swap component names. */
function componentBadge(name: string): FrameNode {
  const f = frame('component-badge');
  f.fills = [fill('#F0F0F0')];
  f.cornerRadius = 4;
  hStack(f, 5, 7, 4);

  const icon = figma.createText();
  icon.fontName = { family: 'Inter', style: 'Regular' };
  icon.characters = '◆';
  icon.fontSize = 8;
  icon.fills = [fill('#888888')];
  f.appendChild(icon);

  const label = figma.createText();
  label.fontName = { family: 'Inter', style: 'Medium' };
  label.characters = name;
  label.fontSize = 10;
  label.fills = [fill('#444444')];
  f.appendChild(label);

  return f;
}

/** 1px horizontal rule at the given width. */
function hr(w: number): FrameNode {
  const f = figma.createFrame();
  f.name = 'divider';
  f.fills = [fill('#E6E6E6')];
  f.resize(w, 1);
  return f;
}

// ─── Properties table ─────────────────────────────────────────────────────────

function tableCell(width: number, height: number, child: FrameNode | TextNode): FrameNode {
  const cell = frame('cell');
  cell.layoutMode = 'HORIZONTAL';
  cell.paddingLeft = 12;
  cell.paddingRight = 12;
  cell.primaryAxisAlignItems = 'MIN';     // left
  cell.counterAxisAlignItems = 'CENTER';  // vertical center
  cell.resize(width, height);
  cell.primaryAxisSizingMode = 'FIXED';
  cell.counterAxisSizingMode = 'FIXED';
  child.layoutAlign = 'CENTER';   // vertically center child within the fixed-height cell
  cell.appendChild(child);
  return cell;
}

function buildPropsTable(props: PropInfo[], contentW: number): FrameNode {
  const col3 = contentW - COL1 - COL2;
  const tableW = contentW;
  const ROW_H = 36;

  const table = frame('props-table');
  table.layoutMode = 'VERTICAL';
  table.itemSpacing = 0;
  table.fills = [fill('#FAFAFA')];
  table.cornerRadius = 8;
  table.strokeWeight = 1;
  table.strokes = [fill('#E6E6E6')];
  table.clipsContent = true;
  table.resize(tableW, 100);
  table.primaryAxisSizingMode = 'AUTO';   // height hugs rows
  table.counterAxisSizingMode = 'FIXED';  // width matches contentW

  // Header row
  const headerRow = frame('header-row');
  headerRow.layoutMode = 'HORIZONTAL';
  headerRow.itemSpacing = 0;
  headerRow.fills = [fill('#F0F0F0')];
  headerRow.resize(tableW, ROW_H);
  headerRow.primaryAxisSizingMode = 'AUTO';
  headerRow.counterAxisSizingMode = 'FIXED';

  const colWidths = [COL1, COL2, col3];
  const headers = ['Property', 'Type', 'Values / Default'];
  headers.forEach((h, i) => {
    const t = txt(h, 11, 'Bold', '#6E6E6E');
    t.textAutoResize = 'TRUNCATE';
    t.resize(colWidths[i] - 24, 16);
    headerRow.appendChild(tableCell(colWidths[i], ROW_H, t));
  });
  table.appendChild(headerRow);

  // Data rows
  props.forEach((prop, idx) => {
    const row = frame('row');
    row.layoutMode = 'HORIZONTAL';
    row.itemSpacing = 0;
    row.fills = [fill(idx % 2 === 1 ? '#F7F7F7' : '#FFFFFF')];
    row.resize(tableW, ROW_H);
    row.primaryAxisSizingMode = 'AUTO';
    row.counterAxisSizingMode = 'FIXED';

    // Col 1 — name
    const nameT = txt(prop.name, 12, 'Medium');
    nameT.textAutoResize = 'TRUNCATE';
    nameT.resize(COL1 - 24, 16);
    row.appendChild(tableCell(COL1, ROW_H, nameT));

    // Col 2 — type pill
    const { bg, fg, label } = typeStyle(prop.type);
    row.appendChild(tableCell(COL2, ROW_H, pill(label, bg, fg)));

    // Col 3 — values (expands with docW)
    let col3Child: FrameNode | TextNode;
    if (prop.type === 'INSTANCE_SWAP' && prop.defaultValue) {
      col3Child = componentBadge(prop.defaultValue);
    } else {
      const valStr = prop.options.length > 0 ? prop.options.join(' · ') : `Default: ${prop.defaultValue}`;
      const valT = txt(valStr, 11, 'Regular', '#6E6E6E');
      valT.textAutoResize = 'TRUNCATE';
      valT.resize(col3 - 24, 16);
      col3Child = valT;
    }
    row.appendChild(tableCell(col3, ROW_H, col3Child));

    table.appendChild(row);
  });

  return table;
}

const TYPE_STYLES: Record<string, { bg: string; fg: string; label: string }> = {
  VARIANT: { bg: '#F3EEFF', fg: '#7C3AED', label: 'Variant' },
  BOOLEAN: { bg: '#F0FDF9', fg: '#0D9488', label: 'Boolean' },
  TEXT:    { bg: '#FFFBEB', fg: '#B45309', label: 'Text' },
};

function typeStyle(type: string) {
  return TYPE_STYLES[type] ?? { bg: '#EFF6FF', fg: '#2563EB', label: 'Instance' };
}

// ─── Variant grid ─────────────────────────────────────────────────────────────

function formatVariantName(raw: string): string {
  return raw
    .split(',')
    .map(part => part.split('=').pop()?.trim() ?? part.trim())
    .join(' / ');
}

async function buildVariantGrid(
  componentSet: ComponentSetNode,
  contentW: number,
  maxItems: number,
): Promise<FrameNode> {
  const variants = [...componentSet.children] as ComponentNode[];
  const shown = variants.slice(0, maxItems);

  const grid = frame('variant-grid');
  grid.layoutMode = 'HORIZONTAL';
  grid.layoutWrap = 'WRAP';
  grid.itemSpacing = 16;
  grid.counterAxisSpacing = 20;
  grid.resize(contentW, 100);
  grid.primaryAxisSizingMode = 'FIXED';  // fixed width → wrapping works
  grid.counterAxisSizingMode = 'AUTO';   // height hugs rows

  for (const variant of shown) {
    const wrapper = frame('variant-wrapper');
    wrapper.layoutMode = 'VERTICAL';
    wrapper.itemSpacing = 8;
    wrapper.counterAxisAlignItems = 'CENTER';
    wrapper.primaryAxisSizingMode = 'AUTO';
    wrapper.counterAxisSizingMode = 'AUTO';

    const instance = variant.createInstance();
    instance.layoutAlign = 'INHERIT';
    instance.layoutSizingHorizontal = 'FIXED';
    instance.layoutSizingVertical = 'FIXED';
    wrapper.appendChild(instance);

    const label = txt(formatVariantName(variant.name), 10, 'Regular', '#6E6E6E');
    label.textAutoResize = 'WIDTH_AND_HEIGHT';
    label.textAlignHorizontal = 'CENTER';
    wrapper.appendChild(label);

    grid.appendChild(wrapper);
  }

  return grid;
}

/** Move all children from `from` into `to`, replacing `to`'s existing children. */
function transferChildren(from: FrameNode, to: FrameNode): void {
  for (const child of [...to.children]) child.remove();
  for (const child of [...from.children]) to.appendChild(child);
}

// ─── Doc frame builder ────────────────────────────────────────────────────────

/**
 * Read the user-authored description from the source's existing doc, if any.
 * Returns DESC_PLACEHOLDER when there is no live doc or it was never edited.
 */
async function readExistingDescription(source: BaseNode): Promise<string> {
  const doc = await resolveLiveNode(readSourceDocId(source));
  if (!doc || doc.type !== 'FRAME') return DESC_PLACEHOLDER;
  const section = (doc as FrameNode).findOne(
    (n) => n.type === 'FRAME' && n.name === 'description-section',
  ) as FrameNode | null;
  if (!section) return DESC_PLACEHOLDER;
  const texts = section.children.filter((n) => n.type === 'TEXT') as TextNode[];
  const valueNode = texts[texts.length - 1];
  if (!valueNode) return DESC_PLACEHOLDER;
  const text = valueNode.characters.trim();
  return text && text !== DESC_PLACEHOLDER ? valueNode.characters : DESC_PLACEHOLDER;
}

async function generateDocs(
  nodeId: string,
  options: { includeProps: boolean; includeVariants: boolean; includeNotes: boolean },
) {
  const node = await figma.getNodeByIdAsync(nodeId);
  if (!node) throw new Error('Node not found.');
  if (node.type !== 'COMPONENT' && node.type !== 'COMPONENT_SET') {
    throw new Error('Select a Component or Component Set.');
  }

  await loadFonts();

  const isSet = node.type === 'COMPONENT_SET';
  const comp = node as ComponentNode | ComponentSetNode;
  const descriptionText = await readExistingDescription(comp);

  // ── Step 1: measure widths before building anything ───────────────────────
  const { contentW, docW } = calcWidths(comp);

  const defs = comp.componentPropertyDefinitions ?? {};
  const props: PropInfo[] = await Promise.all(
    Object.entries(defs).map(async ([rawName, def]) => {
      let defaultValue = String(def.defaultValue);
      // Resolve instance swap node IDs → component names
      if (def.type === 'INSTANCE_SWAP' && def.defaultValue) {
        const ref = await figma.getNodeByIdAsync(String(def.defaultValue));
        if (ref) defaultValue = ref.name;
      }
      return {
        name: rawName.includes('#') ? rawName.split('#')[0] : rawName,
        type: def.type as PropInfo['type'],
        options: (def as { variantOptions?: string[] }).variantOptions ?? [],
        defaultValue,
      };
    }),
  );

  const variantCount = isSet ? (comp as ComponentSetNode).children.length : 0;

  // ── Step 2: build doc at computed width ───────────────────────────────────
  const doc = frame(`📄 ${comp.name} — Documentation`);
  doc.fills = [fill('#FFFFFF')];
  doc.cornerRadius = 12;
  doc.strokeWeight = 1;
  doc.strokes = [fill('#E6E6E6')];
  doc.clipsContent = false;
  vStack(doc, docW, 0, 0, 0);

  // Header
  const header = frame('header');
  header.fills = [fill('#F8F8F8')];
  vStack(header, docW, 6, PAD_H, 20);

  const titleRow = frame('title-row');
  hStack(titleRow, 10, 0, 0);
  titleRow.counterAxisAlignItems = 'CENTER';
  titleRow.appendChild(txt(comp.name, 20, 'Bold'));
  titleRow.appendChild(pill(isSet ? 'Component Set' : 'Component', '#EFF6FF', '#2563EB'));
  header.appendChild(titleRow);

  const metaParts: string[] = [];
  if (props.length > 0) metaParts.push(`${props.length} ${props.length === 1 ? 'property' : 'properties'}`);
  if (isSet && variantCount > 0) metaParts.push(`${variantCount} variants`);
  header.appendChild(txt(metaParts.join('  ·  ') || 'No properties', 12, 'Regular', '#6E6E6E'));
  doc.appendChild(header);
  doc.appendChild(hr(docW));

  // Description
  if (options.includeNotes) {
    const hasDesc = descriptionText !== DESC_PLACEHOLDER;
    const notesSection = frame('description-section');
    vStack(notesSection, docW, 8, PAD_H, 20);
    notesSection.appendChild(txt('DESCRIPTION', 10, 'Bold', '#AAAAAA'));
    notesSection.appendChild(
      txt(descriptionText, 13, 'Regular', hasDesc ? '#1A1A1A' : '#CCCCCC'),
    );
    doc.appendChild(notesSection);
    doc.appendChild(hr(docW));
  }

  // Properties
  if (options.includeProps && props.length > 0) {
    const propsSection = frame('properties-section');
    vStack(propsSection, docW, 12, PAD_H, 20);
    propsSection.appendChild(txt(`PROPERTIES (${props.length})`, 10, 'Bold', '#AAAAAA'));
    propsSection.appendChild(buildPropsTable(props, contentW));
    doc.appendChild(propsSection);
  }

  // Variants
  if (options.includeVariants && isSet && variantCount > 0) {
    doc.appendChild(hr(docW));

    const varSection = frame('variants-section');
    vStack(varSection, docW, 16, PAD_H, 20);
    varSection.appendChild(txt(`VARIANTS (${variantCount})`, 10, 'Bold', '#AAAAAA'));

    const MAX_VARIANTS = 24;
    const grid = await buildVariantGrid(comp as ComponentSetNode, contentW, MAX_VARIANTS);
    varSection.appendChild(grid);

    if (variantCount > MAX_VARIANTS) {
      varSection.appendChild(
        txt(`+ ${variantCount - MAX_VARIANTS} more variants not shown`, 11, 'Regular', '#CCCCCC'),
      );
    }

    doc.appendChild(varSection);
  }

  // ── Step 3: place — update existing frame in place, or create a new one ───
  const existingDoc = await resolveLiveNode(readSourceDocId(comp));
  const isUpdate = existingDoc !== null && existingDoc.type === 'FRAME';

  let finalDoc: FrameNode;
  if (isUpdate) {
    const target = existingDoc as FrameNode;
    transferChildren(doc, target); // move freshly built children into the kept frame
    target.name = doc.name;        // refresh name in case the component was renamed
    doc.remove();                  // discard the empty shell
    finalDoc = target;             // position preserved — do NOT reposition
  } else {
    const bounds = comp.absoluteBoundingBox!;
    doc.x = bounds.x + bounds.width + 80;
    doc.y = bounds.y;
    figma.currentPage.appendChild(doc);
    finalDoc = doc;
  }

  linkNodes(comp, finalDoc);
  saveDocMeta(finalDoc, options, descriptionText);

  figma.currentPage.selection = [finalDoc];
  figma.viewport.scrollAndZoomIntoView([finalDoc]);

  return { propCount: props.length, variantCount, mode: isUpdate ? 'update' : 'generate' };
}

// ─── Selection helper ─────────────────────────────────────────────────────────

async function getSelectionInfo() {
  const sel = figma.currentPage.selection;
  if (!sel.length) return null;
  const selected = sel[0];

  // Resolve to the SOURCE component/set. Selecting a doc frame resolves back
  // to its source; selecting a component uses it directly.
  let source: ComponentNode | ComponentSetNode | null = null;
  let docNode: BaseNode | null = null;

  if (selected.type === 'COMPONENT' || selected.type === 'COMPONENT_SET') {
    source = selected as ComponentNode | ComponentSetNode;
    const docId = readSourceDocId(source);
    docNode = await resolveLiveNode(docId);
  } else if (isDocFrame(selected)) {
    const resolvedSource = await resolveLiveNode(readDocSourceId(selected));
    if (
      resolvedSource &&
      (resolvedSource.type === 'COMPONENT' || resolvedSource.type === 'COMPONENT_SET')
    ) {
      source = resolvedSource as ComponentNode | ComponentSetNode;
      docNode = selected;
    }
  }

  if (!source) return null;

  const hasLiveDoc = docNode !== null;
  const defs = source.componentPropertyDefinitions ?? {};

  return {
    id: source.id,
    name: source.name,
    type: source.type,
    propCount: Object.keys(defs).length,
    variantCount: source.type === 'COMPONENT_SET' ? (source as ComponentSetNode).children.length : 0,
    mode: hasLiveDoc ? ('update' as const) : ('generate' as const),
    docId: hasLiveDoc ? docNode!.id : null,
    options: hasLiveDoc ? readDocOptions(docNode!) : null,
  };
}

// ─── Message handler ──────────────────────────────────────────────────────────

figma.ui.onmessage = async (msg: { type: string; [key: string]: unknown }) => {
  if (msg.type === 'init') {
    const info = await getSelectionInfo();
    figma.ui.postMessage(info ? { type: 'context', info } : { type: 'no-selection' });
  }

  if (msg.type === 'generate') {
    try {
      const result = await generateDocs(
        msg.nodeId as string,
        msg.options as { includeProps: boolean; includeVariants: boolean; includeNotes: boolean },
      );
      figma.ui.postMessage({ type: 'done', ...result });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      figma.notify(`Error: ${message}`, { error: true });
      figma.ui.postMessage({ type: 'error', message });
    }
  }

  if (msg.type === 'reveal') {
    const doc = await resolveLiveNode(msg.docId as string);
    if (doc && doc.type === 'FRAME') {
      figma.currentPage.selection = [doc as FrameNode];
      figma.viewport.scrollAndZoomIntoView([doc as FrameNode]);
    }
  }

  if (msg.type === 'close') {
    figma.closePlugin();
  }
};

figma.on('selectionchange', async () => {
  const info = await getSelectionInfo();
  figma.ui.postMessage(info ? { type: 'context', info } : { type: 'no-selection' });
});
